# Generated by Django 5.0.2 on 2024-02-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KudaGo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fri_end',
            field=models.TimeField(null=True, verbose_name='Пятница, время закрытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fri_start',
            field=models.TimeField(null=True, verbose_name='Пятница, время открытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mon_end',
            field=models.TimeField(null=True, verbose_name='Понедельник, время закрытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='mon_start',
            field=models.TimeField(null=True, verbose_name='Понедельник, время открытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sat_end',
            field=models.TimeField(null=True, verbose_name='Суббота, время закрытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sat_start',
            field=models.TimeField(null=True, verbose_name='Суббота, время открытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sun_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Воскресенье, время закрытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sun_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Воскресенье, время открытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='thu_end',
            field=models.TimeField(null=True, verbose_name='Четверг, время закрытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='thu_start',
            field=models.TimeField(null=True, verbose_name='Четверг, время открытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tue_end',
            field=models.TimeField(null=True, verbose_name='Вторник, время закрытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tue_start',
            field=models.TimeField(null=True, verbose_name='Вторник, время открытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wed_end',
            field=models.TimeField(null=True, verbose_name='Среда, время закрытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wed_start',
            field=models.TimeField(null=True, verbose_name='Среда, время открытия'),
        ),
    ]
