# Generated by Django 5.0.2 on 2024-02-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KudaGo', '0003_alter_company_mon_end_alter_company_mon_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fri_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Пятница, время закрытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fri_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Пятница, время открытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sat_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Суббота, время закрытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='sat_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Суббота, время открытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='thu_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Четверг, время закрытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='thu_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Четверг, время открытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tue_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Вторник, время закрытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tue_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Вторник, время открытия'),
        ),
        migrations.AlterField(
            model_name='company',
            name='wed_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Среда, время открытия'),
        ),
    ]
