# Generated by Django 5.0.2 on 2024-03-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KudaGo', '0004_alter_company_fri_end_alter_company_fri_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration_hrs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Продолжительность (часы)'),
        ),
        migrations.AddField(
            model_name='event',
            name='duration_min',
            field=models.IntegerField(blank=True, null=True, verbose_name='Продолжительность (минуты)'),
        ),
    ]
